name: Pillars
version: '1.0-SNAPSHOT'
main: fun.mikolaj0524.pillars.Pillars
api-version: '1.21'
load: POSTWORLD
authors: [ Mikolaj0524 ]
description: plugin
website: https://mikolaj0524.fun
commands:
  luckypillars:
    description: Lucky pillars manage command!